import { Injectable } from '@nestjs/common';
import { GenerateCvDto } from './dto/generate-cv.dto';
import { UsersService } from '../users/users.service';
import { SkillsService } from '../skills/skills.service';
import { QuestionnaireService } from '../questionnaire/questionnaire.service';
import PDFDocument = require('pdfkit');

@Injectable()
export class CvService {
  constructor(
    private readonly usersService: UsersService,
    private readonly skillsService: SkillsService,
    private readonly questionnaireService: QuestionnaireService,
  ) {}

  async generate(dto: GenerateCvDto) {
    const userId = dto.userId ?? 'anonymous';
    const profile = await this.usersService.getProfile(userId);
    const skills = await this.skillsService.getUserSkills(userId);
    const answers = await this.questionnaireService.getLatestAnswers(userId);

    return {
      userId,
      profile,
      headline: dto.headline ?? 'Junior candidate open to opportunities',
      sections: {
        skills,
        interests: answers?.interests ?? [],
        workPreferences: answers?.workPreferences ?? [],
      },
      note: 'JSON CV generated. Use POST /cv/pdf for PDF export.',
    };
  }

  async generatePdf(dto: GenerateCvDto): Promise<Buffer> {
    const userId = dto.userId ?? 'anonymous';
    const profile = await this.usersService.getProfile(userId);
    const skills = await this.skillsService.getUserSkills(userId);
    const answers = await this.questionnaireService.getLatestAnswers(userId);

    const fullName = profile
      ? `${profile.first_name} ${profile.last_name}`
      : 'User';
    const headline =
      dto.headline ?? 'Young professional open to opportunities';

    return new Promise<Buffer>((resolve, reject) => {
      const doc = new PDFDocument({ size: 'A4', margin: 50 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', (err: Error) => reject(err));

      // Header
      doc
        .rect(0, 0, 595.28, 100)
        .fill('#1565C0');

      doc
        .fontSize(28)
        .fillColor('#FFFFFF')
        .text(fullName, 50, 30, { align: 'left' });

      doc
        .fontSize(12)
        .fillColor('#E3F2FD')
        .text(headline, 50, 65, { align: 'left' });

      let y = 120;

      // Contact section
      if (profile) {
        doc.fillColor('#333333');
        y = this.addSection(doc, 'Contact', y);
        if (profile.email) {
          doc.fontSize(11).text(`Email: ${profile.email}`, 50, y);
          y += 18;
        }
        if (profile.telephone) {
          doc.fontSize(11).text(`Phone: ${profile.telephone}`, 50, y);
          y += 18;
        }
        if (profile.ville) {
          doc.fontSize(11).text(`City: ${profile.ville}`, 50, y);
          y += 18;
        }
        if (profile.niveau_scolaire) {
          doc.fontSize(11).text(`Education: ${profile.niveau_scolaire}`, 50, y);
          y += 18;
        }
        y += 10;
      }

      // Skills section
      if (skills.length > 0) {
        y = this.addSection(doc, 'Skills', y);
        for (const skill of skills) {
          doc.fontSize(11).fillColor('#333333').text(`• ${skill}`, 60, y);
          y += 18;
        }
        y += 10;
      }

      // Interests
      const interests = answers?.interests ?? [];
      if (interests.length > 0) {
        y = this.addSection(doc, 'Interests', y);
        doc.fontSize(11).fillColor('#333333').text(interests.join(', '), 60, y);
        y += 20;
      }

      // Work preferences
      const prefs = answers?.workPreferences ?? [];
      if (prefs.length > 0) {
        y = this.addSection(doc, 'Work Preferences', y);
        doc.fontSize(11).fillColor('#333333').text(prefs.join(', '), 60, y);
        y += 20;
      }

      // Footer
      const pageH = doc.page.height;
      doc
        .fontSize(9)
        .fillColor('#999999')
        .text('Generated by E@dmaj App - Fondation CDG', 50, pageH - 40, {
          align: 'center',
        });

      doc.end();
    });
  }

  private addSection(doc: PDFKit.PDFDocument, title: string, y: number): number {
    doc
      .fontSize(14)
      .fillColor('#1565C0')
      .text(title, 50, y);
    y += 20;
    doc
      .moveTo(50, y)
      .lineTo(545.28, y)
      .strokeColor('#1565C0')
      .lineWidth(1)
      .stroke();
    y += 10;
    return y;
  }
}
